imagesv2Set = {
              'cloudos-portal', 'cloudos-param', 'cloudos-openstack-compute', 'cloudos-openstack',
              'cloudos-web-app', 'cloudos-core-api', 'cloudos-db-install', 'cloudos-app-manager',
              'cloudos-postgres', 'nginx', 'cloudos-kube-dns', 'cloudos-rabbitmq', 'registry'
}

#cloudos3.0容器镜像集合
imagesv3Set = {
          "cloudos-openstack-compute",
          "h3cloud-framework/papaya",
          "cloudae-cfy-riemann",
          "cloudae-cfy-nginx",
          "cloudae-cfy-stage",
          "cloudae-cfy-rest",
          "cloudae-cfy-amqp",
          "h3cloud-ae/h3cloudae-core",
          "cloudae-cfy-logstash",
          "cloudae-terraform",
          "cloudae-cfy-influxdb",
          "appmgmt",
          "cloudae-cfy-mgmt",
          "cloudae-app-portal",
          "cloudae-cfy-apporch",
          "h3ccloud/h3cloudos/bingo-service",
          "h3ccloud/h3cloudoc/alert-portal",
          "h3cloud-framework/sultana",
          "h3cloud-framework/cherry",
          "bdaas-ui",
          "h3ccloud/h3cloudos/cloudos-core-api",
          "h3cloud-framework/taurus-core",
          "h3ccloud/h3cloudos/cas-proxy-core",
          "dbaas-nugget-api",
          "nugget-ui",
          "docs/ol-help",
          "cloudae-nugget",
          "h3ccloud/h3cloudos/compute-core",
          "h3ccloud/h3cloudos/netsecurity-core",
          "h3cloud-framework/gemini-core",
          "h3cloud-framework/virgo-core",
          "h3ccloud/h3cloudos/image-core",
          "cloudos-openstack-ceilometer",
          "cloudos-neutron-agent",
          "h3cloud-framework/jujube",
          "cloudos-openstack-glance",
          "h3cloud-framework/wechat-core",
          "h3cloud-os/storage-core",
          "h3cloud-framework/coconut",
          "cloudos-openstack-cinder",
          "cloudos-openstack-sahara",
          "h3cloud-framework/sorb",
          "cloudos-openstack-manila",
          "cloudos-openstack-nova",
          "cloudos-neutron-server",
          "cloudos-openstack-barbican",
          "cloudos-openstack-heat",
          "cloudos-openstack-manila-share",
          "h3ccloud/h3cloudos/cloudos-nginx-gateway",
          "cloudos-openstack-keystone",
          "cloudos-openstack-ironic-api",
          "cloud-base/redis-3.2.4",
          "cloud-base/rabbitmq-3.6.5",
          "h3cloud-framework/leo-core",
          "cloudos-openstack-trove",
          "cloud-base/mysql-mha-5.7-0.58",
          "h3cloud-framework/milk-cdn",
          "h3cloud-framework/cancer-core",
          "h3cloud-framework/sagittarius-core",
          "h3cloud-framework/pisces-core",
          "h3cloud-framework/cloudkitty-core",
          "cloud-base/mha-manager-0.58",
          "h3cloud-framework/pomelo-core",
          "h3cloud-framework/strawberry",
          "cloud-base/maxscale-2.1.7",
          "h3cloud-framework/cas-server",
          "h3cloud-framework/olive",
          "h3cloud-framework/flume",
          "h3cloud-framework/elasticsearch",
          "h3cloud-framework/milk",
          "h3cloud-framework/plum",
          "cloud-ce/grafana",
          "h3cloud-framework/milk-nginx",
          "h3cloud-framework/lemon-core",
          "h3cloud-framework/aries-core",
          "h3cloud-framework/aquarius-core",
          "cloudae-bigdata-core",
          "cloud-base/influxdb",
          "cloudae-database-core",
          "appsync",
          "cloudae-datasrv-portal",
          "h3ccloud/h3cloudoc/cloudoc-autoboot",
          "h3ccloud/h3cloudoc/cloudoc-monitor-service",
          "h3ccloud/h3cloudoc/cloudoc-mq-service",
          "h3ccloud/h3cloudoc/cloudoc-cmdb-service",
          "h3ccloud/h3cloudoc/alert-service",
          "h3ccloud/h3cloudoc/trap-service",
          "h3ccloud/h3cloudoc/cloudoc-topology-service",
          "h3ccloud/h3cloudoc/cloudoc-monitor-config",
          "h3ccloud/h3cloudoc/cloudoc-business",
          "h3ccloud/h3cloudoc/cloudoc-business-exporter",
          "h3ccloud/h3cloudoc/cloudoc-alert-collector",
          "h3ccloud/h3cloudoc/alert-collector",
          "h3ccloud/h3cloudoc/cloudoc-jmx-exporter",
          "h3ccloud/h3cloudoc/cloudoc-alertmanager",
          "h3ccloud/h3cloudoc/cloudoc-host-exporter",
          "h3ccloud/h3cloudoc/cloudoc-dameng-exporter",
          "h3ccloud/h3cloudoc/cloudoc-container-exporter",
          "h3ccloud/h3cloudoc/cloudoc-middleware-exporter",
          "h3ccloud/h3cloudoc/cloudoc-portal",
          "h3ccloud/h3cloudoc/cloudoc-rsa",
          "h3ccloud/h3cloudoc/cloudoc-prometheus",
          "h3ccloud/h3cloudoc/cloudoc-storage-exporter",
          "h3ccloud/h3cloudoc/cloudoc-prom-conf-gen",
          "h3ccloud/h3cloudoc/cloudoc-virtual-exporter",
          "h3ccloud/h3cloudoc/cloudoc-snmp-exporter",
          "cloudboot",
          "h3ccloud/h3cloudoc/cloudoc-db-exporter",
          "nexus",
          "cloudoc-cmdbuild",
          "cloud-base/postgres",
          "cloudos-param",
          "cloud-base/influxdbnginx",
          "h3cloudos-memcached",
          "cloud-ce/heapster",
          "h3cloud/registry",
          "registry",
          "cloudos-kube-dns"
  }

servicedictv2 = {
    "cloudos-openstack": ['ftp-server', 'h3c-agent', 'httpd', 'mongod', 'neutron-server', 'openstack-nova-consoleauth',
                  'openstack-ceilometer-api', 'openstack-ceilometer-collector',
                  'openstack-ceilometer-notification',
                  'openstack-cinder-api', 'openstack-cinder-scheduler', 'openstack-glance-api',
                  'openstack-nova-conductor',
                  'openstack-glance-registry', 'openstack-nova-api', 'openstack-nova-cert',
                  'openstack-nova-novncproxy',
                  'openstack-nova-scheduler'],
    "cloudos-openstack-compute": ['openstack-ceilometer-compute', 'openstack-cinder-volume',
                                  'openstack-neutron-cas-agent',
                                  'openstack-nova-compute']
}

servicedictv3 = {
    "cloudos-openstack-glance": ["ftp-server.service", "openstack-glance-api.service",
                                 "openstack-glance-registry.service"],
    "cloudos-neutron-server": ["neutron-server.service"],
    "cloudos-neutron-agent": ["h3c-agent.service"],
    "cloudos-openstack-ceilometer": ["openstack-ceilometer-api.service", "openstack-ceilometer-collector.service",
                                     "openstack-ceilometer-notification.service"],
    "cloudos-openstack-cinder": ["openstack-cinder-api.service", "openstack-cinder-scheduler.service"],
    "cloudos-openstack-compute": ["openstack-ceilometer-compute.service", "openstack-cinder-volume.service",
                                  "openstack-neutron-cas-agent.service", "openstack-nova-compute.service"],
    "cloudos-openstack-nova": ["openstack-nova-api.service", "openstack-nova-cert.service",
                               "openstack-nova-conductor.service",
                               "openstack-nova-consoleauth.service", "openstack-nova-novncproxy.service",
                               "openstack-nova-scheduler.service"]
}

services = {
    'E1': servicedictv2,
    'E3': servicedictv3
}